baseurl = "https://musale.github.io/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 6

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = true
  enableGitInfo = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  updatedDatePrefix = "Updated On"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  oneHeadingSize = false


[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "m4musale"
  site = "https://musale.github.io"

[languages]
  [languages.en]
    languageName = "English"
    title = "Martin Musale"
    subtitle = "I’m Musale Martin – a learner, problem-solver, and software engineer from Kenya, based in Nairobi. I'm currently building ~~and breaking~~ software at Microsoft in the M365 team."
    owner = "Martin Musale"
    keywords = "Web Development, Software Developer Engineer, Programming, Data Structures and Algorithms"
    copyright = "© 2021 Martin Musale"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "Martin Musale (⌐▨_▨)"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "contacts"
        name = "Contacts"
        url = "/contacts"
		weight = 60
      [[languages.en.menu.main]]
        identifier = "thoughts"
        name = "Thoughts?"
        url = "/thoughts"
		weight = 30
	  [[languages.en.menu.main]]
        identifier = "cv"
        name = "CV"
        url = "/cv"
		weight = 10
	  [[languages.en.menu.main]]
        identifier = "wishlist"
        name = "Wishlist"
        url = "/wishlist"
		weight = 40
	  [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"
		weight = 20
	  [[languages.en.menu.main]]
        identifier = "my-list"
        name = "Bucket List"
        url = "/my-list"
		weight = 50