baseURL = "https://musale.github.io/"
languageCode = "en-us"
title = "Musale Martin"
theme = "hoyt"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "native"
enableEmoji = true
latexDashes = true
googleAnalytics = "UA-154147297-1"

[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 10

[[menu.main]]
	name = "CV"
	url  = "/cv"
	weight = 20

[[menu.main]]
	name = "Projects"
	url  = "/projects"
	weight = 30

[[menu.main]]
	name = "Thoughts?"
	url  = "/thoughts"
	weight = 50

[[menu.main]]
	name = "Bucket List"
	url  = "/my-list"
	weight = 60

[[menu.main]]
	name = "Wishlist"
	url  = "/wishlist"
	weight = 70

[[menu.main]]
	name = "Contact"
	url  = "/contacts"
	weight = 80

[params]
	name = "Martin Musale"
	tagLine = "$ sudo cat /usr/bin/me"
    description = """I’m Musale Martin – a learner, problem-solver, and software engineer from Kenya, based in Nairobi.

I graduated with a BS in Mathematics & Computer Science from [Jomo Kenyatta University of Agriculture and Technology](http://www.jkuat.ac.ke/), where I developed my love for technology and problem-solving.

I'm currently building and breaking software at Microsoft in the 365 team.

I was previously with the Automation and Data Pipelining team at [Libryo](https://libryo.com). We were helping businesses to know their regulations by collecting, tagging, summarising, and giving them notifications when it changes.

Before that, I was with [Optimetriks](https://optimetriks.com), [Gravity](https://gravity.earth), and [Focus Mobile](https://smsleopard.com) – where I helped to make sending bulk SMSs faster and more efficient.

In my free time, I contribute to open source projects. I'm a maintainer at [Encode](https://www.encode.io/) where we aim to develop the highest quality open-source software. At the moment I'm mostly programming in [Python](https://python.org) and [TypeScript](https://typescriptlang.org/), but I enjoy [Go](https://golang.org/) and also learning new languages. My favorites typically change over time.

Currently, I'm into interpreters, how programming languages work, and distributed systems.

When I'm not programming the web, I listen to music ~~and you can tell that I love Rihanna~~ 😉, I [write](/thoughts), travel, [read](https://www.goodreads.com/user/show/13682301-mr-musale), and I imagine myself exercise."""

    avatar = "images/avatar.jpg"
    avatarAlt = "Rihanna"
    avatarTitle = "I love Rihanna"

    [[params.subheading]]
    title = "Projects I've authored"
    description = """I've authored or co-developed some open-source software projects. They now live on their own [projects page](/projects)."""

[params.Utterances]
	repo = "musale/musale.github.io"
