baseURL = "http://example.org/"
languageCode = "en-us"
title = "Musale Martin"
theme = "hoyt"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "native"

[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 10
    title = "Welcome!"

[[menu.main]]
	name = "Resume/CV"
	url  = "/CV"
	weight = 20
    title = "Check my work!"

[[menu.main]]
	name = "Projects"
	url  = "/projects"
	weight = 30
    title = "At work!"

[[menu.main]]
	name = "Blog Posts"
	url  = "/posts"
	weight = 50
    title = "Posted!"

[[menu.main]]
	name = "Contact"
	url  = "/contacts"
	weight = 60
    title = "Welcome!"

[params]
	name = "Martin Musale"
	tagLine = "2 birds, 1 stone"
    description = "I'm married to the only Franci Hoyt in the world, and we and our three lovely daughters live in the New York City metro area. Check out our blog <a href='https://aliensintheapple.com/'>Aliens in the Apple</a> or read some of the <a href='/writings/'>things I've written</a>."

    avatar = "images/avatar.jpg"
    avatarAlt = "Musale on image"
    avatarTitle = "Title of the image"

    [[params.subheading]]
    title = "Other web sites I run"
    description = """<ul>
          <li>
            <a href="https://giftyweddings.com/">Gifty Weddings</a> helps
            couples make great wedding gift registries.
          </li>
          <li>
            <a href="https://aliensintheapple.com/">Aliens in the Apple</a> is
            our family blog, started during our time in NYC.
          </li>
          <li>
            <a href="/prism-magazine/">Prism magazine</a> was a small-scale
            print magazine I edited.
          </li>
        </ul>"""

    [[params.subheading]]
    title = "Projects I've authored"
    description = """<p>
          I&rsquo;ve authored or co-developed a few small open source software
          projects. They now live on their own
          <a href="/projects/">projects page</a>.
        </p>"""