name: Deploy musale.dev

on:
  push:
    branches: [ master ]

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    # Step 1 - Checks-out your repository under $GITHUB_WORKSPACE
    - name: Checkout
      uses: actions/checkout@v4
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
          fetch-depth: 0
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token

    # Step 2 - Sets up the latest version of Hugo
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: 'latest'

    # Step 3 - Clean and don't fail
    # - name: Clean public directory
    #   run: rm -rf public

    # Step 4 - Builds the site using the latest version of Hugo
    # Also specifies the theme we want to use
    - name: Build
      run: hugo --theme=terminal

    # Step 5 - Create name file
    - name: Check out the public submodule folder and commit files
      run: |
        git status
        cd public
        git status
        git config --local user.email "martinmshale@gmail.com"
        git config --local user.name "Musale Martin"
        msg="Rebuilding the site on `date`"
        if [ $# -eq 1 ]
          then msg="$1"
        fi
        git add .
        git commit -m "$msg"
        
    - name: Push changes to musale.github.io
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN_MGI }}
        branch: master
        repository: musale/musale.github.io
        directory: ./public

    - name: Update this repo's submodules
      run: |
        git config --local user.email "martinmshale@gmail.com"
        git config --local user.name "Musale Martin"
        msg="Rebuilding the site on `date`"
        if [ $# -eq 1 ]
          then msg="$1"
        fi
        git add .
        git commit -m "$msg"

    - name: Push changes to musale-dev
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN_MGI }}
        branch: master
    
